// <auto-generated />
using System;
using Enemix.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Enemix.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520093803_LongText")]
    partial class LongText
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Enemix.Models.MaterialEstudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AreaConhecimento")
                        .HasColumnType("integer");

                    b.Property<string>("ConteudoTeorico")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MateriaisEstudo");
                });

            modelBuilder.Entity("Enemix.Models.Questao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlternativaA")
                        .HasColumnType("text");

                    b.Property<string>("AlternativaB")
                        .HasColumnType("text");

                    b.Property<string>("AlternativaC")
                        .HasColumnType("text");

                    b.Property<string>("AlternativaCorreta")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("AlternativaD")
                        .HasColumnType("text");

                    b.Property<string>("AlternativaE")
                        .HasColumnType("text");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MaterialEstudoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resolucao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MaterialEstudoId");

                    b.ToTable("Questoes");
                });

            modelBuilder.Entity("Enemix.Models.TopicoEstudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AreaConhecimento")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoHtml")
                        .HasColumnType("text");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("TopicosEstudo");
                });

            modelBuilder.Entity("Enemix.Models.Questao", b =>
                {
                    b.HasOne("Enemix.Models.MaterialEstudo", "MaterialEstudo")
                        .WithMany("Questoes")
                        .HasForeignKey("MaterialEstudoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialEstudo");
                });

            modelBuilder.Entity("Enemix.Models.MaterialEstudo", b =>
                {
                    b.Navigation("Questoes");
                });
#pragma warning restore 612, 618
        }
    }
}
